# apiVersion: apps/v1
# kind: Deployment # what kind of service/object you want to create


# # What would you like to call this deployment 
# metadata:
#   name: nginx-deployment # naming the deployment 
# spec: 
#   selector:
#     matchLabels:
#           app: nginx-deployment # look for this label to match k8 service 
#   # lets create a replica set of this with 3 instance pods 
#   replicas: 3
#   # template to use its label for k8 service to launch in the browser 
#   template:
#     metadata:
#       labels:
#         app: nginx # this label connects to the service or any other k8 components 
#   # lets define the container spec
#     spec:
#       containers:
#       - name: nginx
#         image: maikszusevics/eng122-maiks
#         ports:
#         - containerPort: 80

apiVersion: apps/v1 # which api to use for deployment
kind: Deployment # what kind of service/object you want to create

# what would you like to call it - name the service/object
metadata:
  name: nginx-deployment # naming the deployment
spec:
  selector:
    matchLabels:
      app: nginx # look for this label to match with k8 service
  
  # Let's create a replica set of this with  instances/pods
  replicas: 3             
    # template to use it's label for K8 service to launch in the browser
  template:
    metadata:
      labels:
        app: nginx # This label connects to 
                   #the service or any other k8 components
  # Let's define the container spec
    spec:
      containers:
      - name: nginx 
        image: maikszusevics/eng122-maiks
        ports:
        - containerPort: 80        