---
# Select the type of API version and type of service/object
apiVersion: v1
kind: Service
# Metadata for name
metadata:  
  name: nginx-svc
  namespace: default # sre  
# Specificaition to include ports Selector to connecto to the deployment
spec:  
  ports:
  - nodePort: 30001 # range is 30000-32768
    port: 80
    
    
    targetPort: 80

# Let's define the selector and label to connect to nginx deployment
  selector:
    app: nginx # this label connects this service to deployment
  
  # Creating NodePort type of deployment
  type: NodePort # also use LoadBalancer -  for local use cluster IP 
