# Create a Diagram for node deployment and service 
# use the example of nginx deployment and service 
# Nodeapp deloyment to have 3pods min - 
# service within the same cluster and namespace to connect-
# to node deploy
# type LoadBalancer
# End goal is to see our node app running port localhost:3000
# The working image of our node-app
# allow port 3000 and 80


apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  replicas: 3
  template: 
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: ahskhan/eng89_node_prod
          
          ports:
            - containerPort: 3000
         # env:
          #  - name: DB_HOST
           #   value: mongodb://10.98.134.193:27017/posts
          
          imagePullPolicy: Always
# add resources required 
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"